### ISSUE TITLE
请问尺寸适配该怎么做呢？

### ISSUE THREAD

**Issue by qiangxi** [zwwill/yanxuan-weex-demo#63]
# 一句话概括
请问大佬怎么做尺寸适配的呢？
# 详细描述
比如`font-size`,`padding`,`width`,'height',`margin`等尺寸大小该如何做适配，这些尺寸官方说只能用`像素px`，但是像素的适配性极差，在native设备上根本没法看，在且样式是写在`style`标签内部的，比如
```css
 .concept-warpper {
        flex-direction: row;
        justify-content: space-between;
        align-items: center;
        background-color: white;
        width: 750px;
        padding-top: 20px;
        padding-right: 20px;
        padding-bottom: 20px;
        padding-left: 20px;
        border-bottom-color: #eeeeee;
        border-bottom-width: 1px;
    }
```
怎么做到在Android&ios&web三端适配呢？从google搜索也没找到好的解决方式，有个方法是要修改webpack的配置，但作为小白根本不会啊，真心恳请大佬解答一下~万分感激！
